FROM dunglas/frankenphp:1.11.2-php8.5
RUN install-php-extensions intl
ENV FRANKENPHP_WORKER=1
COPY Caddyfile.worker /etc/frankenphp/Caddyfile
COPY . /app
RUN php tempest discovery:generate
RUN php tempest migrate-and-seed